// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmdUFVHMd4Ovu7DnFG6UGdtYfXxxpdng',
    appId: '1:272574714476:web:37ca83bf05cb214161be49',
    messagingSenderId: '272574714476',
    projectId: 'umadose',
    authDomain: 'umadose.firebaseapp.com',
    storageBucket: 'umadose.firebasestorage.app',
    measurementId: 'G-57XZNPFBL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNxyKRDnVc91kPs-qpInNfOZHOUejjk9Q',
    appId: '1:272574714476:android:3942e34606e98d7161be49',
    messagingSenderId: '272574714476',
    projectId: 'umadose',
    storageBucket: 'umadose.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztFjdm8h1jEbPPMC1aeUR0WrFJf9dQXM',
    appId: '1:272574714476:ios:153233956ee13bd661be49',
    messagingSenderId: '272574714476',
    projectId: 'umadose',
    storageBucket: 'umadose.firebasestorage.app',
    iosClientId: '272574714476-77rdpm6uetehlj5okp6281q24av2pv0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.umadose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztFjdm8h1jEbPPMC1aeUR0WrFJf9dQXM',
    appId: '1:272574714476:ios:153233956ee13bd661be49',
    messagingSenderId: '272574714476',
    projectId: 'umadose',
    storageBucket: 'umadose.firebasestorage.app',
    iosClientId: '272574714476-77rdpm6uetehlj5okp6281q24av2pv0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.umadose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrmdUFVHMd4Ovu7DnFG6UGdtYfXxxpdng',
    appId: '1:272574714476:web:742206575c7898a761be49',
    messagingSenderId: '272574714476',
    projectId: 'umadose',
    authDomain: 'umadose.firebaseapp.com',
    storageBucket: 'umadose.firebasestorage.app',
    measurementId: 'G-NWPTK9Z145',
  );
}
